server:
  port: 8086
  servlet:
    context-path:

path:
  pic: src/main/resources/static/pic/
  doc: src/main/resources/static/doc/

spring:
  servlet:
    multipart:
      # enabled: false
      max-request-size: 10MB
      max-file-size: 1MB